In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest,chi2,RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv(r'https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Pima.csv', index_col=0)
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
test=SelectKBest(score_func=chi2,k=5)
chi=test.fit(x,y)

In [7]:
chi.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [8]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [9]:
chidf = pd.DataFrame(chi.scores_).T
chidf.columns = x.columns

In [10]:
chidf

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

# RFE

In [11]:
lg= LogisticRegression()

rfe=RFE(lg,n_features_to_select=5)

rfe.fit(x,y)

RFE(estimator=LogisticRegression(), n_features_to_select=5)

In [12]:
rfe.support_

array([ True,  True, False, False, False,  True,  True,  True])

In [13]:
rfe_df=pd.DataFrame(rfe.ranking_).T
rfe_df.columns=x.columns
rfe_df

preg  plas  pres  skin  test  mass  pedi  age
0     1     1     2     3     4     1     1    1

# Tree Based Approach

In [14]:
dt= DecisionTreeClassifier(criterion='entropy')

In [15]:
dt.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [16]:
dt_df=pd.DataFrame(dt.feature_importances_).T
dt_df.columns=x.columns
dt_df

preg     plas      pres      skin      test      mass      pedi  \
0  0.095229  0.23509  0.089608  0.020228  0.046733  0.260261  0.123238   

        age  
0  0.129614

- Univariate selection:
    - Test,Plasma,Age,Mass
    
- RFE:
    - preg,plas,mass,pedi,age
    
- Tree:
    - Plasma,mass,pedi,age

# Cross validation 

In [17]:
from sklearn.model_selection import KFold , LeaveOneOut, cross_val_score

In [18]:
kf= KFold(n_splits=10,random_state=1,shuffle=True)
score=cross_val_score(LogisticRegression(),x,y,cv=kf)

In [19]:
score.mean()

0.7720608339029391

In [20]:
#Leave one out

In [21]:
df.shape

(768, 9)

In [22]:
le= LeaveOneOut()
le_score= cross_val_score(LogisticRegression(),x,y,cv=le)

In [23]:
le_score

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [24]:
le_score.mean()

0.7786458333333334